---
title: "Environmental Features"
author: "Ford Fishman"
date: "4/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data

```{r}
require("corrplot")
require("dplyr")
require("reshape2")
require("vegan")
# data table
df <- read.table("~/GitHub/QBVirus/data/env-geo-div-class.txt", sep = "\t", header = TRUE,row.names = 1)
vcs.o <-read.csv("~/GitHub/QBVirus/data/vcs.csv", row.names = 1)

# numerical features
num_cols <- unlist(lapply(df, is.numeric))

# numerical df
df.num <- df[, num_cols]
```

# Correlations

```{r}
cor1 <- cor(df.num[,1:9], use="complete.obs")
corrplot(cor1, method = "ellipse")
```
```{r}
vcs <- as.data.frame(t(vcs.o))
#convert to relative abundance table
vcs.rel <- vcs/rowSums(vcs)
# top20 VCs
top <- names(head(sort(colSums(vcs),decreasing = T),20))
top <- as.vector(top)
# recreate a table with the rest VCs classified into "Others"
vcs.rel2 <- vcs.rel
colnames(vcs.rel2)[!colnames(vcs.rel2)%in%top] <- "Others"
others <- rowSums(cbind(vcs.rel2[colnames(vcs.rel2)=="Others"]))
vcs.top <- cbind(vcs.rel2[colnames(vcs.rel2)!="Others"],others)
vcs.top <- vcs.top[,order(colSums(vcs.top))] # ranking
#load group data
env.class.geo.div <- df
vcs.top2 <- as.data.frame(cbind(vcs.top,env.class.geo.div$Layer,env.class.geo.div$Region))
vcs.top2$sample <- rownames(vcs.top2)
vcs.top20 <- melt(vcs.top2,ID="names")
colnames(vcs.top20)[names(vcs.top20)=="variable"]<-"Taxa"
vcs.top20$`env.class.geo.div$Layer` <- factor(vcs.top20$`env.class.geo.div$Layer`, levels = c("SUR","DCM","MIX","MES")) #set order
# group by layer(zonation)
vcs.top.layer <- aggregate(vcs.top2[,1:21], by = list(Layer = vcs.top2$`env.class.geo.div$Layer`),FUN = mean)
vcs.top.layer$sample <- rownames(vcs.top.layer)
vcs.group.layer <- melt(vcs.top.layer, ID="names")
colnames(vcs.group.layer)[names(vcs.group.layer)=="variable"]<-"Taxa"
vcs.group.layer$Layer <- factor(vcs.group.layer$Layer, levels = c("SUR","DCM","MIX","MES")) #set order
# group by region
vcs.top.region <- aggregate(vcs.top2[,1:21], by = list(Layer = vcs.top2$`env.class.geo.div$Region`),FUN = mean)
vcs.top.region$sample <- rownames(vcs.top.region)
vcs.group.region <- melt(vcs.top.region, ID="names")
colnames(vcs.group.region)[names(vcs.group.region)=="variable"]<-"Taxa"
```
```{r}
library(oce)
data(coastlineWorld)
par(mar=c(1.5, 1.5, 0.5, 0.5))
mapPlot(coastlineWorld, col="lightgrey")
mapPoints(df.num$Longitude_E, df.num$Latitude_N, pch=19, col="red")
```

```{r}
vcs.db <- vegdist(vcs.rel, method="bray")

vcs.pcoa <- cmdscale(vcs.db, eig=T, k=3)

eig.sum <- sum(vcs.pcoa$eig)

explainvar1 <- round( vcs.pcoa$eig[1]/eig.sum, 3)*100
explainvar2 <- round( vcs.pcoa$eig[2]/eig.sum, 3)*100
explainvar3 <- round( vcs.pcoa$eig[3]/eig.sum, 3)*100
sum.eig <- explainvar1+explainvar2+explainvar3

par(mar=c(5,5,1,2)+0.1)
plot(vcs.pcoa$points[,1], vcs.pcoa$points[,2], 
     xlab=paste0("PCoA 1 (", explainvar1,"%)"),
     ylab=paste0("PCoA 2 (", explainvar2,"%)"),
     pch=16, cex=2.0, type="n", cex.lab=1.5, cex.axis=1.2, axes=F)

axis(side=1, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
axis(side=2, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
abline(h=0, v=0, lty=3)

points(vcs.pcoa$points[,1], vcs.pcoa$points[,2], pch=19, cex=2, bg="grey",col="grey")
```
```{r}
vcs.ward <- hclust(vcs.db, method = "ward.D2")
par(mar=c(1,5,2,2)+0.1)
plot(vcs.ward,labels=FALSE,ylab="Squared Bray-Curtis")
```

# imputation
```{r}
require(mice)
require(VIM)
df.num1 <- subset(df.num, ! rownames(df.num) %in% c("MSP114"))
df.sparse <- subset(df.num1, select=-c(Richness,Evenness,ShannonH))

mice_plot <- aggr(df.sparse, col=c('grey','white'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(df.sparse), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```
```{r}
df.sparse <- subset(df.sparse, select=-c(Nitrate))
imputed_Data <- mice(df.sparse, m=1, maxit = 100, method = 'pmm')
summary(imputed_Data)
```

```{r}
completeData <- complete(imputed_Data,1)
write.csv(completeData, file = "~/GitHub/QBVirus/data/metadata-imputed.csv")
```

# RDA
```{r}
require(ggplot2)
vcs <- subset(vcs, ! rownames(vcs) %in% c("MSP114"))
df1 <- subset(df, ! rownames(df) %in% c("MSP114"))


# numerical features
num_cols <- unlist(lapply(df, is.numeric))

# numerical df
df.num <- df1[, num_cols]
df.sparse <- subset(df.num, select=-c(Richness,Evenness,ShannonH))


#convert to relative abundance table
vcs.rel <- vcs/rowSums(vcs)
vcs.db <- vegdist(vcs.rel, method="bray")

vcs.pcoa <- cmdscale(vcs.db, eig=T, k=3)

pcoa2_eig <- (vcs.pcoa$eig)[1:2]/sum(vcs.pcoa$eig)
site.pcoa <- data.frame(vcs.pcoa$points)[1:2]
site.pcoa <- cbind(site.pcoa, df1$Layer)
colnames(site.pcoa) <- c("PCoA1","PCoA2","Layer")

ggplot(site.pcoa, aes(PCoA1, PCoA2))+
  geom_point(aes(color = Layer), size = 2)+
  scale_color_brewer(palette = "Set2")+
  labs(x=paste("PCoA1: ", round(100*pcoa2_eig[1],2),"%"), y = paste("PCoA2: ", round(100*pcoa2_eig[2],2),"%")) +
      theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.ticks.length = unit(5,"pt"),)
```

```{r}
env.data <- read.csv("~/GitHub/QBVirus/data/metadata-imputed.csv", row.names = 1)
dbrda1 <- dbrda(vcs.db ~ ., as.data.frame(env.data))
dbrda0 <- dbrda(vcs.db ~ 1, as.data.frame(env.data))

dbrda <- ordiR2step(dbrda0, scope=formula(dbrda1), perm.max=200)

permutest(dbrda, permutations=999)
envfit(dbrda, env.data[,c(4,6,7)], perm=999)

dbrda.explainvar1 <- round(dbrda$CCA$eig[1]/sum(c(dbrda$CCA$eig, dbrda$CA$eig)),3) * 100
dbrda.explainvar2 <- round(dbrda$CCA$eig[2]/sum(c(dbrda$CCA$eig, dbrda$CA$eig)),3) * 100


vals <- scores(dbrda, display="wa")
par(mar=c(5,4,2,4) + 0.1)
plot(vals, 
     xlim=c(-1, 2), ylim=c(-2.5, 2.2),
     xlab=paste0("dbRDA 1 (", dbrda.explainvar1, "%)"),
     ylab=paste0("dbRDA 2 (", dbrda.explainvar2, "%)"),
     pch=16, cex=2.0, type="n", cex.lab=1.5, cex.axis=1.2, axes=F
)
axis(side=1, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
axis(side=2, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
abline(h=0, v=0, lty=3)
box(lwd=2)

points(vals, pch=19, cex=2, bg="grey", col="grey")

vectors <- scores(dbrda, display = "bp")
arrows(0, 0, vectors[,1], vectors[,2], lwd=2, lty=1, length = 0.2, col = "red")
text(vectors[,1], vectors[,2], pos=4, labels=row.names(vectors))
axis(side=3, lwd.ticks = 2, cex.axis=1.2, las=1, col="red", lwd=2.2, 
     at = pretty(range(vectors[,1]))*2, labels = pretty(range(vectors[,1])))
axis(side=4, lwd.ticks = 2, cex.axis=1.2, las=1, col="red", lwd=2.2, 
     at = pretty(range(vectors[,2]))*2, labels = pretty(range(vectors[,2])))


```

## Remove deepest samples

```{r}
vcs.shal <- subset(vcs, df1$Layer!="MES")
env.shal <- subset(env.data, df1$Layer!="MES")
layers <- subset(df1, Layer!="MES", select="Layer")
```

## Redo ordination without `MES`

```{r}
vcs.shal.rel <- vcs.shal/rowSums(vcs.shal)
vcs.shal.db <- vegdist(vcs.shal.rel, method="bray")

vcs.shal.pcoa <- cmdscale(vcs.shal.db, eig=T, k=3)

pcoa3_eig <- (vcs.shal.pcoa$eig)[1:2]/sum(vcs.shal.pcoa$eig)
site.shal.pcoa <- data.frame(vcs.shal.pcoa$points)[1:2]
site.shal.pcoa <- cbind(site.shal.pcoa, layers)
colnames(site.shal.pcoa) <- c("PCoA1","PCoA2","Layer")

ggplot(site.shal.pcoa, aes(PCoA1, PCoA2))+
  geom_point(aes(color = Layer), size = 2)+
  scale_color_brewer(palette = "Set2")+
  labs(x=paste("PCoA1: ", round(100*pcoa3_eig[1],2),"%"), y = paste("PCoA2: ", round(100*pcoa3_eig[2],2),"%")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.ticks.length = unit(5,"pt"),)
```
```{r}
dbrda1.shal <- dbrda(vcs.shal.db ~ ., as.data.frame(env.shal))
dbrda0.shal <- dbrda(vcs.shal.db ~ 1, as.data.frame(env.shal))

dbrda.shal <- ordiR2step(dbrda0.shal, scope=formula(dbrda1.shal), perm.max=200)

permutest(dbrda.shal, permutations=999)
envfit(dbrda.shal, env.shal, perm=999)

dbrda.explainvar1.shal <- round(dbrda.shal$CCA$eig[1]/sum(c(dbrda.shal$CCA$eig, dbrda.shal$CA$eig)),3) * 100
dbrda.explainvar2.shal <- round(dbrda.shal$CCA$eig[2]/sum(c(dbrda.shal$CCA$eig, dbrda.shal$CA$eig)),3) * 100


vals.shal <- scores(dbrda.shal, display="wa")
par(mar=c(5,4,2,4) + 0.1)
plot(vals.shal, 
     xlim=c(-1.75, 1.75), ylim=c(-2, 2.2),
     xlab=paste0("dbRDA 1 (", dbrda.explainvar1.shal, "%)"),
     ylab=paste0("dbRDA 2 (", dbrda.explainvar2.shal, "%)"),
     pch=16, cex=2.0, type="n", cex.lab=1.5, cex.axis=1.2, axes=F
)
axis(side=1, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
axis(side=2, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
abline(h=0, v=0, lty=3)
box(lwd=2)

points(vals.shal, pch=19, cex=2, bg="grey", col="grey")

vectors.shal <- scores(dbrda.shal, display = "bp")
arrows(0, 0, vectors.shal[,1], vectors.shal[,2], lwd=2, lty=1, length = 0.2, col = "red")
text(vectors.shal[,1], vectors.shal[,2], pos=4, labels=row.names(vectors.shal))
axis(side=3, lwd.ticks = 2, cex.axis=1.2, las=1, col="red", lwd=2.2, 
     at = pretty(range(vectors.shal[,1]))*2, labels = pretty(range(vectors.shal[,1])))
axis(side=4, lwd.ticks = 2, cex.axis=1.2, las=1, col="red", lwd=2.2, 
     at = pretty(range(vectors.shal[,2]))*2, labels = pretty(range(vectors.shal[,2])))
```
# The deep samples
```{r}
vcs.deep <- subset(vcs, df1$Layer=="MES")
env.deep <- subset(env.data, df1$Layer=="MES")

vcs.deep.rel <- vcs.deep/rowSums(vcs.deep)
vcs.deep.db <- vegdist(vcs.deep.rel, method="bray")

dbrda1.deep <- dbrda(vcs.deep.db ~ ., as.data.frame(env.deep))
dbrda0.deep <- dbrda(vcs.deep.db ~ 1, as.data.frame(env.deep))

dbrda.deep <- ordiR2step(dbrda0.deep, scope=formula(dbrda1.deep), perm.max=200)

permutest(dbrda.deep, permutations=999)
envfit(dbrda.deep, env.deep, perm=999)

dbrda.explainvar1.deep <- round(dbrda.deep$CCA$eig[1]/sum(c(dbrda.deep$CCA$eig, dbrda.deep$CA$eig)),3) * 100
dbrda.explainvar2.deep <- round(dbrda.deep$CCA$eig[2]/sum(c(dbrda.deep$CCA$eig, dbrda.deep$CA$eig)),3) * 100


vals.deep <- scores(dbrda.deep, display="wa")
par(mar=c(5,4,2,4) + 0.1)
plot(vals.deep, 
     xlim=c(-1.75, 1.75), ylim=c(-2, 2.2),
     xlab=paste0("dbRDA 1 (", dbrda.explainvar1.deep, "%)"),
     ylab=paste0("dbRDA 2 (", dbrda.explainvar2.deep, "%)"),
     pch=16, cex=2.0, type="n", cex.lab=1.5, cex.axis=1.2, axes=F
)
axis(side=1, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
axis(side=2, labels=T, lwd.ticks=2, cex.axis=1.2, las=1)
abline(h=0, v=0, lty=3)
box(lwd=2)

points(vals.deep, pch=19, cex=2, bg="grey", col="grey")

vectors.deep <- scores(dbrda.deep, display = "bp")
arrows(0, 0, vectors.deep[,1], vectors.deep[,2], lwd=2, lty=1, length = 0.2, col = "red")
text(vectors.deep[,1], vectors.deep[,2], pos=4, labels=row.names(vectors.deep))
axis(side=3, lwd.ticks = 2, cex.axis=1.2, las=1, col="red", lwd=2.2, 
     at = pretty(range(vectors.deep[,1]))*2, labels = pretty(range(vectors.deep[,1])))
axis(side=4, lwd.ticks = 2, cex.axis=1.2, las=1, col="red", lwd=2.2, 
     at = pretty(range(vectors.deep[,2]))*2, labels = pretty(range(vectors.deep[,2])))
```

